# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7k160tfbg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.cache/wt [current_project]
set_property parent.project_path C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib mylib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library mylib {
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/SiTCP/SiTCP_XC7K_32K_BBT_V90.V
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/SiTCP/TIMER.v
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/SiTCP/WRAP_SiTCP_GMII_XC7K_32K.V
}
read_vhdl -library mylib {
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/UserParameters.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/BPS_2bits.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/BPS_6bits.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/BPS_7bits.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/BusController.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/DCR_NetAssign_Out.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/DLY.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/DPWM.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/EDG.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/FDLY.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/IOManager_NIM.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/LED_Module.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/PS.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/PWC.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/PWCbig.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/Region1.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/Region2_1.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/Region2_2.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/Region2_3.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/Region2_4.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/Region2_5.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/Region2_6.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/Region3.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/Region4.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/TCP_sender.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/global_sitcp_manager.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/modules/synchronizer.vhd
  C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/toplevel.vhd
}
read_ip -quiet C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all c:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci]

read_ip -quiet C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_edif C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/sources_1/SiTCP/SiTCP_XC7K_32K_BBT_V90.ngc
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/constrs_1/hul_pins.xdc
set_property used_in_implementation false [get_files C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/constrs_1/hul_pins.xdc]

read_xdc C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/constrs_1/hul_timing.xdc
set_property used_in_implementation false [get_files C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/constrs_1/hul_timing.xdc]

read_xdc C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/constrs_1/hul_target.xdc
set_property used_in_implementation false [get_files C:/Users/suharu/Desktop/FPGA/HUL_Trigger_IOM1234_extraline/HUL_Trigger_IOM1234_extraline.srcs/constrs_1/hul_target.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top toplevel -part xc7k160tfbg676-1


write_checkpoint -force -noxdef toplevel.dcp

catch { report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb }
